# Generated by Django 4.2.11 on 2026-05-15 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chatmessage',
            new_name='chatbot_cha_user_id_753d9c_idx',
            old_name='chatbot_cm_user_dt_idx',
        ),
        migrations.RenameIndex(
            model_name='chatmessage',
            new_name='chatbot_cha_session_f839ac_idx',
            old_name='chatbot_cm_sess_dt_idx',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sentiment',
            field=models.FloatField(default=0.0),
        ),
    ]
